language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:gstreamer-developers/ppa -y
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo apt-get update -qq

install:
  - >
    sudo apt-get install -qq libpthread-stubs0-dev libgl1-mesa-dev libx11-dev
    libxrandr-dev libfreetype6-dev libglew1.5-dev libjpeg8-dev libgpgme11-dev
    libsndfile1-dev libopenal-dev libudev-dev
    libgstreamer1.0-dev
    libglib2.0-dev
    libboost-thread1.54-dev libboost-locale1.54-dev
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi

before_script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - cd ..
  - git clone --depth 1 https://github.com/LaurentGomila/SFML.git
  - cd SFML
  - cmake . -DSFML_BUILD_EXAMPLES=FALSE -DSFML_BUILD_DOC=FALSE
  - make -j2
  - sudo make install
  - cd ..
  - git clone --depth 1 https://github.com/FGRE/libnpa.git
  - cd libnpa
  - cmake .
  - make
  - cd ../libnpengine

script:
  - cmake .
  - make
