language: cpp

compiler:
  - gcc
  - clang

env:
  # this is our secret upload key $SECRET_TOKEN:
  secure: "UdtY0QDaL3kLuhJDPCEwTBKn4fV5SBpgGGnuUnwfj9gJ1oCnKrCZGvbvl+gkHgmWVPc/lnbVTrbxWGOmppO+WtARjiKMlBhkyhkcoLxmUK5+zXl45IZWS1n94i//hu24PM+pkgGJliDlwl1vTu6k0G+iJj4TigNyAd6WUiHAkc0="

branches:
  only:
    - master

notifications:
  email:
    on_success: change
    on_failure: change
  irc:
    channels:
      - "chat.freenode.net#fgre"
    on_success: change
    on_failure: change
    use_notice: true
    skip_join: true

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:gstreamer-developers/ppa
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get update -qq

install:
  - >
    sudo apt-get install -qq libpthread-stubs0-dev libgl1-mesa-dev libx11-dev
    libxrandr-dev libfreetype6-dev libglew1.5-dev libjpeg8-dev libgpgme11-dev
    libsndfile1-dev libopenal-dev libudev-dev
    libgstreamer-plugins-base1.0-dev
    libglib2.0-dev
    libboost-locale1.55-dev
    lftp
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq libstdc++-4.8-dev; fi

before_script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
  - git clone --depth 1 https://github.com/LaurentGomila/SFML.git ../sfml
  - cd ../sfml
  - cmake . -DSFML_BUILD_EXAMPLES=FALSE -DSFML_BUILD_DOC=FALSE && make -j2 && sudo make install
  - cd .. && mkdir libnpa && cd libnpa
  - curl http://dev.pulsir.eu/krofna/downloads/latest.php?p=libnpa | tar jx --strip-components=1
  - cd $TRAVIS_BUILD_DIR

script:
  - cmake . && make

after_success:
  - make package
  - curl https://gist.githubusercontent.com/carstene1ns/a23f152a40a589f098c6/raw/upload.sh > upload.sh
  - bash upload.sh libnpengine-*.tar.bz2
